### ISSUE TITLE
Not working when plugin name contains spaces

### ISSUE THREAD

**Issue by jbeckers** [thepieterdc/intellij-plugin-verifier-action#10]
Please advise on how to make the action work when the plugin name contains spaces.

See the commit history for a list of my failed attempts:
https://github.com/jbeckers/CompareTabWithEditor2/blob/master/.github/workflows/plugin-verifier.yml

**Comment by thepieterdc** [comment]
Thank you for reporting this issue. I will make a fork of your repository within a few hours and devise a solution, I'll keep you posted.

**Comment by thepieterdc** [comment]
@jbeckers I have opened a PR on your repository that fixes this issue. The fix is to place the * before the space.
