### ISSUE TITLE
cannot find zipfile directory in one of ideaIU-2020.2.2.zip

### ISSUE THREAD

**Issue by bluelovers** [thepieterdc/intellij-plugin-verifier-action#11]
[ideaIU-2020.2.2.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ideaIU-2020.2.2.zip or
        ideaIU-2020.2.2.zip.zip, and cannot find ideaIU-2020.2.2.zip.ZIP, period.

**Comment by YannCebron** [comment]
There is no version "2020.2.2" but only "2020.2".
